version: '3'
services:
  api:
    container_name: spl-api
    restart: always
    build: .
    ports:
      - '8080:80'
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ynYDTI2v
      POSTGRES_USER: spl_user
      PGDATA: /var/lib/postgresql/mydata #needed because of some weird permissions error
      POSTGRES_DB: ScrumPokerLive
    ports:
      - '5433:5432' #5433 to not block postgres port if you have it setup localy